name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.1
      - name: Install Dependencies
        run: |
          cd webapp 
          npm install
      - name: Build FrontEnd
        run: |
          cd webapp
          npm run build
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Deploy with Gradle
        run: ./gradlew deployGithub
      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: 92.205.163.207
          username: ${{secrets.username}}
          password: ${{secrets.password}}
          port: 22
          uploads: |
            deploy/ => ../var/www/html
      - name: stop ktor backend
        uses: appleboy/ssh-action@v1.2.0
        continue-on-error: true
        with:
          host: 92.205.163.207
          username: ${{secrets.username}}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: screen -X -S "ktor-backend" quit
      - name: start ktor backend
        uses: appleboy/ssh-action@v1.2.0
        continue-on-error: true
        with:
          host: 92.205.163.207
          username: ${{secrets.username}}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ../var/www/html
            screen -S "ktor-backend" java -jar ktor.jar