name: Build

on: [ push ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.1
      - name: Install Dependencies
        run: |
          cd webapp 
          npm install
      - name: Build FrontEnd
        run: |
          cd webapp
          npm run build
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Deploy with Gradle
        run: ./gradlew deployGithub
      - name: SFTP Upload
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: "92.205.163.207"
          remote-user: ${{secrets.username}}
          remote-password: ${{secrets.password}}
          remote-port: 22
          sync: full
          local-path: "/deploy"
          remote-path: "./var/www/html/test"


