name: Build_Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.1
      - name: Install Dependencies
        run: |
          cd webapp 
          npm install
      - name: Build FrontEnd
        run: |
          cd webapp
          npm run build
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ac2d340dc04d9e1113182899e983b5400c17cda1
      - name: Deploy with Gradle
        run: ./gradlew deployGithub
      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@50ed7273493353a60dace713957c36b02dd87bec
        with:
          server: 92.205.163.207
          username: ${{secrets.username}}
          password: ${{secrets.password}}
          port: 22
          uploads: |
            deploy/ => ../var/www/html
      - name: stop and start ktor backend
        uses: appleboy/ssh-action@7eaf76671a0d7eec5d98ee897acda4f968735a17
        continue-on-error: true
        with:
          host: 92.205.163.207
          username: ${{secrets.username}}
          password: ${{ secrets.password }}
          port: 22
          script: |
            cd ../var/www/html
            kill $(cat ktor.pid)
            chmod +x ktor.jar
            nohup java -jar ktor.jar > ktor.log 2>&1 &
            echo $! > ktor.pid