name: Build

on: [ push ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.1
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
      - name: Deploy with Gradle
        run: ./gradlew deploy
      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
         server: 92.205.163.207
         username: ${{secrets.username}}
         password: ${{secrets.password}}
         port: 22
         uploads: |
          ./deploy => ./var/www/html